# Generated by Django 5.2.9 on 2025-12-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='prevention_tips',
            field=models.TextField(blank=True, help_text='Line-separated prevention tips'),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Line-separated symptoms'),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment',
            field=models.TextField(blank=True, help_text='Line-separated treatment steps'),
        ),
    ]
