# Generated by Django 6.0 on 2025-12-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_prescriptiontemplate_symptomtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='treatment',
        ),
    ]
