# Generated by Django 6.0 on 2025-12-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_disease_symptoms_remove_disease_treatment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['name'], 'verbose_name_plural': 'Diseases'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='prescriptiontemplate',
            options={'ordering': ['text']},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='symptomtemplate',
            options={'ordering': ['text']},
        ),
        migrations.AddField(
            model_name='disease',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['disease', 'order'], name='api_prescri_disease_5447bb_idx'),
        ),
        migrations.AddIndex(
            model_name='symptom',
            index=models.Index(fields=['disease', 'order'], name='api_symptom_disease_be1262_idx'),
        ),
    ]
